"""Daily run: load candidates, fetch the trailing window once, invoke the graph.

Bars are fetched once for the whole batch rather than per candidate — the graph
nodes close over the resulting frame, which keeps them pure and testable.
"""

from __future__ import annotations

import asyncio
import csv
from datetime import date, timedelta
from uuid import uuid4

import aiosqlite
import pandas as pd
from langgraph.cache.memory import InMemoryCache
from langgraph.checkpoint.serde.jsonplus import JsonPlusSerializer
from langgraph.checkpoint.sqlite.aio import AsyncSqliteSaver

from lagmatrix.adapters.candidates import ExternalSignals
from lagmatrix.adapters.market import MarketFeed
from lagmatrix.domain.models import Assessment, Bar, Candidate, Evidence, LagEdge, NewsChunk, Shock
from lagmatrix.graph.builder import build_graph
from lagmatrix.graph.context import LagMatrixContext

TRAIL_PAD = 130  # calendar days ≈ 90 sessions, over the 60 the nodes need
EXCLUDED_ETFS_PATH = "data/excluded-etfs.csv"
CHECKPOINT_DB_PATH = "data/checkpoints.sqlite"

# D-44: allowlisted per (module, class name) so checkpointed state round-trips
# as domain models instead of dicts, without the "unregistered type" warning.
_ALLOWED_MODELS = [
    ("lagmatrix.domain.models", cls.__name__)
    for cls in (Bar, Shock, LagEdge, NewsChunk, Candidate, Evidence, Assessment)
]


def _load_excluded_symbols(path: str = EXCLUDED_ETFS_PATH) -> frozenset[str]:
    """Leveraged/inverse products to keep out of correlation neighbourhoods.

    Generated by scripts/build_exclusions.py; a fresh clone won't have it,
    so a missing file just means no exclusions rather than a hard failure.
    """
    try:
        with open(path) as fh:
            return frozenset(row["symbol"] for row in csv.DictReader(fh))
    except FileNotFoundError:
        return frozenset()


async def run(
    as_of: date | None = None,
    *,
    closes: pd.DataFrame | None = None,
    universe: list[str] | None = None,
    with_news: bool = True,
    limit: int | None = None,
    thread_id: str | None = None,
    halt_on_contradicted: bool = False,
    signals: ExternalSignals | None = None,
) -> tuple[list, str, dict | None]:
    """Assess the candidates for `as_of` (all of them when None).

    Returns `(assessments, thread_id, interrupt)` — the run is checkpointed
    under `thread_id`, so the id must come back to the caller or the run is
    not replayable (`scripts/replay.py`). `interrupt` is the `review` node's
    payload (D-19) when `halt_on_contradicted` paused the run on a
    contradicted verdict, `None` otherwise — the default path never
    interrupts, so this is `None` unless the caller opted in. `signals`
    injects the candidate source, defaulting to `ExternalSignals()`.
    """
    thread_id = thread_id or f"{as_of or 'all'}-{uuid4().hex[:8]}"
    signals = signals or ExternalSignals()
    all_candidates = signals.candidates(as_of)
    candidates = all_candidates[:limit] if limit else all_candidates
    if not candidates:
        return [], thread_id, None

    signal_universe = {c.symbol for c in all_candidates}
    # Q-37: union in the shocked leaders that originated scan candidates, the
    # same way scripts/serve.py does, so a leader's own move can't be counted
    # as evidence for the candidate it produced. Duck-typed because
    # ExternalSignals has no shocked_leaders and the protocol shouldn't force
    # scan-only machinery onto every source.
    if hasattr(signals, "shocked_leaders") and as_of is not None:
        signal_universe |= set(signals.shocked_leaders(as_of))

    if closes is None:
        start = min(c.as_of for c in candidates) - timedelta(days=TRAIL_PAD)
        end = max(c.as_of for c in candidates)
        syms = sorted(set(universe or []) | signal_universe)
        closes = MarketFeed().daily_closes(syms, start, end)

    ctx = LagMatrixContext(
        closes=closes,
        signal_universe=signal_universe,
        excluded_symbols=_load_excluded_symbols(),
        halt_on_contradicted=halt_on_contradicted,
    )
    config = {"configurable": {"thread_id": thread_id}}

    # One invocation for the whole batch: candidates fan out per-branch inside
    # the graph (Send), keyed so a batch cannot cross-attribute one
    # candidate's neighbours to another.
    serde = JsonPlusSerializer(allowed_msgpack_modules=_ALLOWED_MODELS)
    async with aiosqlite.connect(CHECKPOINT_DB_PATH) as conn:
        saver = AsyncSqliteSaver(conn, serde=serde)
        # A fresh cache per run: its lifetime matches `closes`' lifetime, which
        # is the mitigation for the stale-neighbourhood hazard noted in
        # build_graph's docstring (PHASE-4 / D-35 item 4).
        graph = build_graph(with_news=with_news, checkpointer=saver, cache=InMemoryCache())
        state = await graph.ainvoke({"candidates": candidates}, context=ctx, config=config)
    interrupts = state.get("__interrupt__")
    interrupt_payload = interrupts[0].value if interrupts else None
    return state.get("assessments", []), thread_id, interrupt_payload


def run_sync(*args, **kwargs) -> tuple[list, str, dict | None]:
    """Sync wrapper for callers (`scripts/run_pipeline.py`) that are not `async`."""
    return asyncio.run(run(*args, **kwargs))
